-- 회고 글
CREATE TABLE thinking_tbl
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    category   ENUM('LEARNED', 'LACKED', 'GOOD') NOT NULL,
    title      VARCHAR(255) NOT NULL,
    content    TEXT         NOT NULL,
    password   VARCHAR(255) NOT NULL,
    like_count INT          NOT NULL DEFAULT 0,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO thinking_tbl (category, title, content, password, like_count, created_at)
VALUES ('LEARNED', 'JPA N+1 문제 해결 과정', 'Fetch Join을 사용하여 지연 로딩 문제를 해결했습니다. 데이터가 깔끔하게 1번만 조회되니 속도가 정말 빨라지네요.', '1234',
        15, '2026-06-01 10:00:00'),
       ('LACKED', '자바스크립트 비동기 처리 미숙', 'Promise와 async/await의 실행 순서가 아직 헷갈립니다. 에러 핸들링을 놓쳐서 화면이 멈추는 버그가 있었습니다.', '5678',
        2, '2026-06-02 14:20:00'),
       ('GOOD', '팀원과의 원활한 소통', 'API 명세서를 미리 상세히 작성하고 공유했더니 프론트엔드 팀원과의 협업이 정말 매끄럽게 진행되었습니다.', 'asdf', 45,
        '2026-06-03 09:15:00'),
       ('LEARNED', 'MySQL 인덱스 적용기', '조회 쿼리가 너무 느려 실행 계획(EXPLAIN)을 확인하고 복합 인덱스를 추가했습니다. 성능이 5배나 향상되었습니다.', 'qwer', 32,
        '2026-06-04 18:30:00'),
       ('LACKED', '예외 처리(Exception Handling) 누락', '컨트롤러단에서 발생하는 모든 예외를 잡아주지 못해 사용자에게 500 에러 페이지가 그대로 노출되는 실수를 했습니다.',
        '9999', 0, '2026-06-05 11:45:00'),
       ('GOOD', '깃허브 PR 템플릿 도입', 'PR 템플릿을 만들어 적용하니 코드 리뷰할 때 어떤 부분을 중점적으로 봐야 하는지 명확해져서 리뷰 속도가 빨라졌습니다.', '0000', 18,
        '2026-06-06 16:00:00'),
       ('LEARNED', 'Docker를 활용한 환경 격리', '로컬 개발 환경과 배포 환경의 OS 차이로 인한 오류를 Docker 컨테이너 도입을 통해 완벽하게 해결했습니다.', 'pass', 24,
        '2026-06-07 13:10:00'),
       ('LACKED', '단위 테스트 코드 작성 부족', '시간이 부족하다는 핑계로 테스트 코드를 소홀히 했더니, 리팩토링할 때 다른 기능이 깨지는 사이드 이펙트가 발생했습니다.', 'test', 5,
        '2026-06-08 22:05:00'),
       ('GOOD', '배포 자동화(CI/CD) 성공', 'GitHub Actions와 AWS를 연동하여 마스터 브랜치에 푸시하면 자동으로 배포되도록 구축했습니다. 수동 배포의 고통에서 해방!',
        'clean', 50, '2026-06-09 17:40:00'),
       ('LEARNED', 'Redis를 이용한 세션 관리', '서버 다중화 환경을 고려하여 Spring Session과 Redis를 연동해 세션을 정합성 있게 관리하는 방법을 배웠습니다.', '9876',
        12, '2026-06-10 11:20:00'),
       ('LACKED', 'CSS Flexbox 레이아웃 꼬임', '반응형 웹을 구현하는 과정에서 Flexbox 속성을 잘못 이해하여 모바일 화면에서 UI가 와장창 깨지는 현상이 발생했습니다.',
        'css1', 1, '2026-06-11 15:50:00'),
       ('GOOD', '매일 아침 데일리 스크럼 진행', '5분씩 진행한 스크럼 덕분에 서로의 진행 상황과 블로킹 이슈를 빠르게 파악할 수 있어서 프로젝트 지연을 막았습니다.', 'daily', 28,
        '2026-06-12 09:05:00'),
       ('LEARNED', 'Spring Security JWT 인증', 'Stateless한 인증을 구현하기 위해 JWT 발급 및 검증 로직을 구현했습니다. Filter 구조를 깊게 이해하게 되었습니다.',
        'jwt!', 37, '2026-06-13 20:15:00'),
       ('LACKED', '하드코딩된 설정 정보들', 'API 키값과 DB 패스워드를 application.yml에 그대로 노출시켰습니다. 다음부터는 꼭 환경변수(`ENV`) 처리를 해야겠습니다.',
        'secret', 8, '2026-06-14 14:00:00'),
       ('GOOD', '일정 산정 및 관리 성공', '기능별로 마일스톤을 쪼개어 무리하지 않게 일정을 산정했더니, 데드라인을 넘기지 않고 안정적으로 기능을 완성했습니다.', 'plan', 19,
        '2026-06-15 18:22:00'),
       ('LEARNED', 'RESTful API 설계 규칙',
        'URI는 명사 위주로, 행위는 HTTP Method(GET, POST, PUT, DELETE)로 표현하는 올바른 API 설계 방식을 체득했습니다.', 'rest', 41,
        '2026-06-16 10:30:00'),
       ('LACKED', 'Git 브랜치 전략 부재', 'Git Flow 같은 전략 없이 모두가 main 브랜치에서 직접 작업하다가 대규모 컨플릭트(Conflict)가 발생해 3시간을 날렸습니다.',
        'git1', 14, '2026-06-17 12:00:00'),
       ('GOOD', '꼼꼼한 API 문서화', 'Swagger(Springdoc)를 도입하여 백엔드 코드가 바뀔 때마다 API 문서가 자동으로 갱신되도록 설정해 협업 효율을 극대화했습니다.', 'swag',
        29, '2026-06-17 16:45:00'),
       ('LEARNED', '유효성 검증(Validation) 적용',
        '@Valid 어노테이션과 BindingResult를 사용해 Request Body의 잘못된 값이 들어오는 것을 컨트롤러 진입 전 차단했습니다.', 'valid', 21,
        '2026-06-18 11:00:00'),
       ('LACKED', '코드 가독성 저하', '한 메서드가 100줄이 넘어가도록 스파게티 코드를 짰습니다. 단일 책임 원칙(SRP)을 지키며 메서드를 분리하는 연습이 절실합니다.', 'clean', 3,
        '2026-06-18 15:30:00');